# Generated by Django 5.1.1 on 2024-10-01 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_drink_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='image',
        ),
        migrations.CreateModel(
            name='DrinkImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.drink')),
            ],
        ),
    ]
