# Generated by Django 5.1.2 on 2024-10-09 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_user_id_order_user_remove_drink_contents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='alcohol_percentage',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
