# Generated by Django 5.1.2 on 2024-10-09 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_drinkorder_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_recived_time',
            new_name='order_received_time',
        ),
    ]
